<?xml version="1.0" encoding="UTF-8"?>
<!-- Mike Broman - 9-25-2026 -->

<!-- TigerTech A2 - categories schema. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cat="http://tigertech.example/categories"
           targetNamespace="http://tigertech.example/categories"
           elementFormDefault="qualified">

   <xs:simpleType name="nonEmptyStringType">
      <xs:restriction base="xs:token">
         <xs:minLength value="1"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="catIDType">
      <xs:restriction base="xs:string">
         <xs:pattern value="CAT-[A-Z]{2,5}"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:complexType name="categoryType">
      <xs:sequence>
         <xs:element name="name" type="cat:nonEmptyStringType"/>
         <xs:element name="blurb" type="cat:nonEmptyStringType"/>
      </xs:sequence>
      <xs:attribute name="catID" type="cat:catIDType" use="required"/>
   </xs:complexType>

   <xs:complexType name="categoriesType">
      <xs:sequence>
         <xs:element name="category" type="cat:categoryType"
                     minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="categories" type="cat:categoriesType"/>

</xs:schema>
